### ISSUE TITLE
[Feature Request] Add the rest of the WS2812FX effects

### ISSUE THREAD

**Issue by cooljimy84** [OttoWinter/esphomedocs#111]
Is there any plans to add more effects (all of them) from the library https://github.com/kitesurfer1404/WS2812FX that you have started using ?

**Comment by OttoWinter** [comment]
Wrong repo, please post this issue here: https://github.com/OttoWinter/esphomelib

And no, I don't have any plans to add them at this point. I don't use these addressable lights myself so it isn't a priority of mine. Plus it'd need to wait for https://github.com/OttoWinter/esphomelib/pull/243 to be ready

I'd be happy to accept PRs that add more effects though.
