### ISSUE TITLE
Details about uploading firmware manually

### ISSUE THREAD

**Issue by fabaff** [OttoWinter/esphomedocs#23]
If esphomeyaml is not able to upload the firmware to the device then uploading it manually with `esptool` could be option. The "alternative upload" is mentioned at a couple of places but no concrete example given. 

I think that it might be handy for users to have those information at hand because of 
https://github.com/OttoWinter/esphomeyaml/issues/121 or because of wired button press pattern to get the device into flash mode. Use the standard settings for an ESP32 don't seem to always work.

**Comment by OttoWinter** [comment]
Good idea. That should definitely be in the docs. The only thing that's stopping me from doing it right away is I don't really know where to put it. I don't really want to put it in the setup guide itself since that should be kept as simple as possible. The other option would be the FAQ page, but from my experience few people actually read that.

From a user perspective (+ active hass docs contributor 🥇 ), what would you recommend?

**Comment by fabaff** [comment]
From my point of view, it a match for the FAQ section. Putting it into the docs would only causes confusion.

**Comment by OttoWinter** [comment]
For the ESP8266, flashing is quite simple with `esptool.py` (though the installation of that can be a bit difficult if you have to install it on a windows machine 🙄)

For the ESP32, however it is a bit more complicated. Usually, you would only have to flash the firmware to `0x10000`, but on the first flash it's also good to replace the old bootloader with a new one at offset `0x8000` + sometimes esphomeyaml also needs to modify the partition table to make more space ... So a simple command to do it all doesn't really exist.

I'm now working on a small python GUI app that does all that for the user and will be available in platform-specific binaries so that the installation is also not a problem.

**Comment by OttoWinter** [comment]
Closing as per #76

**Comment by velocyped** [comment]
I really would like to know where this is documented.
Someone stated here that it has nothing to do in FAQ, but it is the only documentation Google finds about manually uploading firmware.
Actually Google also finds a second result which is this issue...
