### ISSUE TITLE
rules of component name defination

### ISSUE THREAD

**Issue by voicevon** [OttoWinter/esphomedocs#94]
https://esphomelib.com/esphomeyaml/guides/automations.html#templates-lambdas

I am following the sample. The name section is very confused to me. The first name `name: "Cover End Stop"` There is a double quote , The second name `name: Living Room Cover` without the double quote, Any reason there?  What rule can I follow?

**Comment by OttoWinter** [comment]
Both are interpreted the same way. In general, to be 100% safe you can put quotes around the values. But it's a feature of YAML that in the cases where you have pure strings (for example names) it is not required.

Please see https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml for further reference.

Since the esphomeyaml validators will tell you when you *have* to put quotes around a value I don't think this is a big problem for the docs.
